# Name of the GitHub Actions workflow
name: iOS CI

# Defines when this workflow should run
on:
  pull_request:
    branches:
      # PR → main → CI runs
      # If PR already running PR updates → CI automatically runs again
      - main

# Defines the work that will be executed
jobs:
  build-and-test: # Is a custom name
    runs-on: xcode-27 # runs-on is the runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6 # GitHub's official reusable action that checks out our repository on the runner's workspace.

      - name: Verify runner
        run: echo "Running CI on macOS"

      - name: Check Xcode version
        run: xcodebuild -version

      - name: List installed Xcode versions
        run: ls /Applications | grep Xcode

      - name: Build iOS App
        # Build GitHubActionsDemo.xcodeproj
        # Scheme - GitHubActionsDemo
        # Build on simulator, concrete simulator is not required
        # Code signing allowed is NO as we do not have Apple Developer account
        run: |
          xcodebuild build \
            -project GitHubActionsDemo.xcodeproj \
            -scheme GitHubActionsDemo \
            -sdk iphonesimulator \
            CODE_SIGNING_ALLOWED=NO

      # Run test case on specific simulator
      # For running test cases concrete simulator is required
      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -project GitHubActionsDemo.xcodeproj \
            -scheme GitHubActionsDemo \
            -destination 'platform=iOS Simulator,name=iPhone 18 Pro,OS=27.0' \
            -only-testing:GitHubActionsDemoTests \
            -enableCodeCoverage YES \
            -resultBundlePath TestResults.xcresult \
            CODE_SIGNING_ALLOWED=NO

      - name: Show Code Coverage
        run: xcrun xccov view --report TestResults.xcresult
